#=========================================================================
#config.yml
#=========================================================================
#Yaml-based configuratin file of PyOCN for modeling, testing,
#and evaluating.
#
#Author : Cheng Tan
#  Date : July 30, 2019
#
---

action:
#  - simulate
  - generate

topology:
  # - Ring
  - Mesh
  # - Torus
  # - Bfly

model:
  # - CL
  - RTL

# For generation (packets):
packets: [
  {
    src: 1,
    dest: 9,
    data: 255
  },
]

# For simulation:
injection:
  # - 0.2
  - 0.4

pattern:
  # - urandom
  - complement

nodes: 16
rows: 4
channel_lat: 0

...
